# Generated by Django 3.2.9 on 2021-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblog',
            name='data_time',
            field=models.DateTimeField(max_length=150),
        ),
    ]
